spring.application.name=whattoeat-server

spring.profiles.active=${SPRING_PROFILES_ACTIVE}

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

jwt.private-key-base64=${JWT_PRIVATE_KEY_BASE64}
jwt.public-key-base64=${JWT_PUBLIC_KEY_BASE64}
jwt.access-token-ttl=5m
jwt.refresh-token-ttl=30d